### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Redis Pub-Sub Message Test
POST http://localhost:8080/send
content-type: application/json

{
  "author": "kim",
  "message": "hello world"
}

### GET MemberData on Spring Server
GET http://localhost:8080/member/1


### GET MemberData on NginX
GET http://localhost/member/1

### PATCH -> Member StatusMessage Change
PATCH http://localhost:8080/member/1
content-type: application/json

{
  "message": "i am son"
}
