spring:
  config:
    import: secret.yml

  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/lock_example?user=root
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6